apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dynatrace-operator
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: dynatrace-operator
    namespace: dynatrace
  values:
    webhook:
      requests:
        cpu: 75m
        memory: 128Mi
      limits:
        cpu: 75m
        memory: 128Mi
