apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example-voting-app
resources:
  - namespace.yml
  - deployment-db.yml
  - deployment-redis.yml
  - deployment-result.yml
  - deployment-vote.yml
  - deployment-worker.yml
  - svc-db.yml
  - svc-redis.yml
  - svc-result.yml
  - svc-vote.yml
  - ingress-result.yml
  - ingress-vote.yml
